name: Hello World

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Chackout code
            uses: actions/checkout@v2

            - name: Echo Hello World
            run: echo "Hello World"